/*
 * File: app/store/Posicoes.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ShSolutions.store.Posicoes', {
    extend: 'Ext.data.Store',

    requires: [
        'ShSolutions.model.Posicoes'
    ],

    config: {
        model: 'ShSolutions.model.Posicoes',
        storeId: 'Posicoes',
        proxy: {
            type: 'jsonp',
            url: urlPrincipal+'server/modulos/posicoes/list.php',
            actionMethods: {
                create: 'POST',
                read: 'POST',
                update: 'POST',
                destroy: 'POST'
            },
            extraParams: {
                action: 'LIST',
                cliente_id: 0,
                platform: device.platform
            },
            reader: {
                type: 'json',
                rootProperty: 'dados'
            }
        }
    }
});