/*
 * File: app/view/Principal.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ShSolutions.view.Principal', {
    extend: 'Ext.Panel',
    alias: 'widget.principal',

    requires: [
        'ShSolutions.view.login.Login',
        'ShSolutions.view.posicoes.List',
        'ShSolutions.view.posicoes.Mapa'
    ],

    config: {
        fullscreen: true,
        id: 'PrincipalContainer',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'SDSAT',
                items: [
                    {
                        xtype: 'button',
                        ui: 'plain',
                        action: 'menu',
                        iconCls: 'list'
                    },
					{
                        xtype: 'button',
						hidden: true,
						id: 'back_list',
                        action: 'back_list',
                        ui: 'plain',
                        iconCls: 'arrow_left'
                    }
                ]
            },
            {
                xtype: 'login'
            },
            {
                xtype: 'posicoeslist'
            },
            {
                xtype: 'posicoesmapa'
            }
        ]
    }

});