/*
 * File: app/model/Posicoes.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ShSolutions.model.Posicoes', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'veiculo_desc'
            },
            {
                name: 'ponto_prox'
            },
            {
                name: 'data'
            },
            {
                name: 'veiculo_id'
            },
            {
                name: 'status'
            },
            {
                name: 'falha_alim_ext'
            },
            {
                name: 'gps'
            },
            {
                name: 'gprs'
            },
            {
                name: 'img_panico'
            },
            {
                name: 'img_bloq'
            },
            {
                name: 'latitude'
            },
            {
                name: 'longitude'
            },
            {
                name: 'velocidade'
            }
        ]
    }
});