/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ShSolutions.controller.Login', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'login.Login'
        ],

        control: {
			'login toolbar button[action=login]' : {
				tap: 'login'
			}
        }
    },

    mask: function(msg){
    	if(msg){
	    	Ext.Viewport.setMasked({
	    		xtype:'loadmask',
	    		message: msg
	    	});
    	}
    	else{
    		Ext.Viewport.setMasked(false);
    	}
    },
	
	login: function(button){
		var me = this;
		
		ShSolutions.app.getController('Principal').checkAjax();
		
		Ext.device.Storage.setItem('isLogged', false);
		var obj = Ext.getCmp('FormLogin').getValues();
		if(obj.login=="" || obj.senha==""){
			return true;
		}
		obj.action = 'LOGIN';
		obj.platform = device.platform;
		me.mask('Aguarde..');
		Ext.util.JSONP.request({
			params: obj,
			url: urlPrincipal+'server/modulos/login/login.php',
			callbackKey: 'callback',
			scope: this,
			success: function(o) {
				me.mask(false);
				if(o.success==true){
					window.usuario_info = o.dados;
					Ext.device.Storage.setItem('isLogged', true);
					ShSolutions.app.getController('Posicoes').showList();
				}
				else{
					Ext.Msg.alert('Erro!', o.msg);
				}
			},

			failure: function(response) {
				me.mask(false);
				Ext.Msg.alert('Erro!', response);
			}
		});
	}
});