/*
 * File: app/view/posicoes/Mapa.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ShSolutions.view.posicoes.Mapa', {
    extend: 'Ext.Panel',
    alias: 'widget.posicoesmapa',

    config: {
        layout: {
            type: 'fit'
        },
        id: 'MapaPanel',
        items: [
            {
                xtype: 'map',
                id: 'MapaView',
                mapOptions: {
                    center: new google.maps.LatLng(37.381592, -122.135672),
                    zoom: 12,
                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                    navigationControl: true,
                    navigationControlOptions: {
                        style: google.maps.NavigationControlStyle.DEFAULT
                    }
                }
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'datepickerfield',
                        centered: true,
                        label: 'Periodo',
                        dateFormat: 'd/m/Y',
                        value: new Date(),
                        id: 'posicoes_periodo',
                        name: 'posicoes_periodo',
                        picker: {
                            useTitles: true,
                            dayText: 'Dia',
                            monthText: 'Mês',
                            slotOrder: [
                                'day',
                                'month',
                                'year'
                            ],
                            yearText: 'Ano',
                            doneButton: {
                                xtype: 'button',
                                id: 'btn_search',
                                text: 'Pesquisar'
                            },
                            cancelButton: 'Cancelar'
                        }
                    }
                ]
            }
        ]
    }

});